FEATURES = [
    'EXT_SOURCE_3', 'EXT_SOURCE_2', 'EXT_SOURCE_1', 'AMT_PAYMENT_min', 'CODE_GENDER', 'AMT_PAYMENT_sum', 'AMT_GOODS_PRICE', 'NAME_EDUCATION_TYPE', 
    'AMT_ANNUITY', 'ORGANIZATION_TYPE', 'AMT_CREDIT', 'OWN_CAR_AGE', 'DAYS_EMPLOYED', 'OCCUPATION_TYPE', 'AMT_CREDIT_SUM_DEBT_mean', 'CNT_INSTALMENT_FUTURE_mean', 
    'NAME_FAMILY_STATUS', 'DAYS_CREDIT_mean', 'CNT_PAYMENT_max', 'DAYS_ID_PUBLISH', 'CNT_PAYMENT_mean', 'AMT_DOWN_PAYMENT_sum', 'DAYS_BIRTH', 'FLAG_DOCUMENT_3', 
    'AGE', 'DAYS_CREDIT_max', 'DAYS_ENTRY_PAYMENT_max', 'REGION_RATING_CLIENT_W_CITY', 'DAYS_ENDDATE_FACT_max', 'DAYS_CREDIT_ENDDATE_max', 'AMT_CREDIT_MAX_OVERDUE_mean', 
    'SK_DPD_DEF_mean_x', 'CNT_DRAWINGS_ATM_CURRENT_mean', 'DAYS_LAST_DUE_1ST_VERSION_max', 'MONTHS_BALANCE_max_x', 'CNT_PAYMENT_sum', 'DAYS_INSTALMENT_max', 'DEF_30_CNT_SOCIAL_CIRCLE', 
    'SK_ID_PREV_sum_y', 'AMT_CREDIT_SUM_sum', 'NFLAG_INSURED_ON_APPROVAL_mean', 'RATE_DOWN_PAYMENT_max', 'AMT_PAYMENT_mean', 'CNT_DRAWINGS_CURRENT_mean', 'AMT_REQ_CREDIT_BUREAU_QRT', 
    'SELLERPLACE_AREA_mean', 'DAYS_ENTRY_PAYMENT_min', 'NAME_INCOME_TYPE', 'WALLSMATERIAL_MODE', 'NAME_CONTRACT_TYPE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'TOTALAREA_MODE', 'AMT_BALANCE_mean', 
    'AMT_CREDIT_MAX_OVERDUE_sum', 'CNT_DRAWINGS_CURRENT_max', 'AMT_CREDIT_SUM_mean', 'DAYS_INSTALMENT_min', 'DAYS_LAST_DUE_mean', 'NUM_INSTALMENT_VERSION_max', 'AMT_CREDIT_sum', 
    'NUM_INSTALMENT_NUMBER_mean', 'CNT_INSTALMENT_mean', 'NUM_INSTALMENT_VERSION_sum', 'AMT_CREDIT_SUM_LIMIT_max', 'SK_ID_PREV_sum_x', 'AMT_CREDIT_SUM_max', 'WEEKDAY_APPR_PROCESS_START',
    'NUM_INSTALMENT_NUMBER_max', 'AMT_CREDIT_SUM_DEBT_sum', 'AMT_GOODS_PRICE_min'
]

PARAMETERS = {
    'num_estimators': 142,
    'learning_rate': 0.1261689397241983,
    'extra_params': {
        'num_leaves': 36,
        'max_depth': 375,
        'min_data_in_leaf': 69,
        'bagging_fraction': 0.7812134356069105,
        'feature_fraction': 0.6116389811545921,
        'num_threads': 650,
        'objective': 'binary',
        'seed': 123,
        'verbose': -1
    }
}